version: '3'

services:
  back-end:
    build: .
    restart: always
    hostname: back-end-service
    container_name: back-end
    ports:
      - 8090:8090
    network_mode: "bridge"
    command: ["sh", "-c", "java -Dspring.profiles.active=prod -jar /back-end.jar"]