server:
  port: 8090
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: eafrey
    password: eafreypwd
    url: jdbc:mysql://localhost:3306/eafrey?createDatabaseIfNotExist=true&useSSL=false&rewriteBatchedStatements=true

logging:
  file: /opt/back-end/back-end-server.log
