server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: eafrey
    password: eafreypwd
    url: jdbc:mysql://localhost:3306/eafrey?createDatabaseIfNotExist=true